In [1]:
import numpy as np 

In [5]:
A = np.array([[1,-1,1],[3,1,2],[-5,2,-1]])
B = np.array([10,34,-14])
x = np.linalg.solve(A,B)
print(A)
print(100*'-')
print(B)
print(100*'-')
print(x)

[[ 1 -1  1]
 [ 3  1  2]
 [-5  2 -1]]
----------------------------------------------------------------------------------------------------
[ 10  34 -14]
----------------------------------------------------------------------------------------------------
[ 2.  4. 12.]
